# Generated by Django 4.0.5 on 2022-07-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='person',
        ),
    ]
