# Generated by Django 4.0.5 on 2022-07-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_person_password_remove_person_user_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mail',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
