# Generated by Django 4.0.5 on 2022-07-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_person_mail_person_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='website',
        ),
    ]
