from django.db import models
from app.models import person
# Create your models here.
from django.db import models
# Create your models here.

class Post(models.Model):
    # id = models.AutoField(primary_key=True)     # generated by default 
    text = models.CharField(max_length=140, blank=True, null=True)  # null == None, blank = ''
    image = models.ImageField(upload_to='post_images')   # BASE_DIR -> media -> post_images
    user = models.ForeignKey(person, on_delete=models.PROTECT, editable=False)    # user_id
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

   


# Comments Model
class Comment(models.Model):
    text = models.CharField(max_length=240)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(person, on_delete=models.CASCADE, editable=False)
    commented_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

   

# Likes Model
class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(person, on_delete=models.CASCADE, editable=False)
    liked_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.post.id)

   

# Followers Model
class Follow(models.Model):
    user = models.ForeignKey(person, related_name='follow_follower', on_delete=models.CASCADE, editable=False)
    followed = models.ForeignKey(person, related_name='follow_followed', on_delete=models.CASCADE)
    followed_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f"{self.user}-->{self.followed}"

    


